import argparse
import json
from pathlib import Path

from ultralytics import YOLO


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description='Evaluate YOLOv8 model.')
    parser.add_argument('--weights', type=str, required=True, help='Path to trained weights (.pt)')
    parser.add_argument('--data', type=str, default='data.yaml', help='Path to data.yaml')
    parser.add_argument('--imgsz', type=int, default=640, help='Evaluation image size')
    parser.add_argument('--split', type=str, default='test', choices=['val', 'test'], help='Dataset split')
    parser.add_argument('--project', type=str, default='outputs/demo_results', help='Output directory')
    parser.add_argument('--name', type=str, default='evaluation', help='Run name')
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    out_dir = Path(args.project) / args.name
    out_dir.mkdir(parents=True, exist_ok=True)

    model = YOLO(args.weights)
    metrics = model.val(
        data=args.data,
        split=args.split,
        imgsz=args.imgsz,
        project=args.project,
        name=args.name,
        plots=True,
        save_json=True,
        exist_ok=True,
    )

    summary = {
        'precision': float(metrics.box.mp),
        'recall': float(metrics.box.mr),
        'map50': float(metrics.box.map50),
        'map50_95': float(metrics.box.map),
    }

    print('Evaluation metrics:')
    print(f"Precision      : {summary['precision']:.4f}")
    print(f"Recall         : {summary['recall']:.4f}")
    print(f"mAP@0.5        : {summary['map50']:.4f}")
    print(f"mAP@0.5:0.95   : {summary['map50_95']:.4f}")

    summary_path = out_dir / 'metrics_summary.json'
    with summary_path.open('w', encoding='utf-8') as f:
        json.dump(summary, f, indent=2)

    print(f'Metrics summary saved to: {summary_path}')
    print('Confusion matrix image is generated by Ultralytics in the same run folder.')


if __name__ == '__main__':
    main()
